# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maYnqqh7eraomeSFn17JX82xqycxSW7t
"""






import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("Vegetation Change Detection & Forecast")

st.subheader("NDVI Forecast")
forecast_df = pd.read_csv("/content/drive/MyDrive/ndvi_lstm_forecast.csv")
st.line_chart(forecast_df.set_index('Date'))

import rasterio
import matplotlib.pyplot as plt

# Read GeoTIFF
with rasterio.open("/content/drive/MyDrive/classified_ndvi_change.tif") as src:
    data = src.read(1)

# Save to PNG
plt.imsave("/content/ndvi_change_map.png", data, cmap='bwr')  # or any other colormap like 'RdYlGn'

st.subheader("Spatial Change Map (UNet)")
#st.image("/content/drive/MyDrive/classified_ndvi_change.tif")
st.image("/content/ndvi_change_map.png", caption="UNet-based Vegetation Change Map")

